services:
  ergondata-site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GOOGLE_GENERATIVE_AI_API_KEY=AIzaSyDar5-PpYWclMEyWwngvaej3nJipqBa_3A
      - GEMINI_API_KEY=AIzaSyDar5-PpYWclMEyWwngvaej3nJipqBa_3A
    restart: unless-stopped
    container_name: ergondata-site
